config/routes.rb
Rails.application.routes.draw do

  resources :song_histories do
    resources :song_versions, except: :index
  end

end

app/models/song_history.rb
class SongHistory < ActiveRecord::Base
  has_many :song_versions, :dependent => :delete_all
end

app/models/song_version.rb
class SongVersion < ActiveRecord::Base
  belongs_to :song_history
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_histories
  has_many :song_histories, :through => :user_histories
end

app/models/user_history.rb
class UserHistory < ActiveRecord::Base
  belongs_to :user
  belongs_to :song_history
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/song_histories_controller.rb
class SongHistoriesController < ApplicationController

  def index
    @song_histories = SongHistory.all
  end

  def new
    @song_history = SongHistory.new
  end

  def create
    @song_history = SongHistory.create(create_params)
    redirect_to song_histories_path
  end

  def edit
    song_history
  end

  def update
    @song_history = SongHistory.update(params[:id], update_params)
    redirect_to song_histories_path
  end

  def destroy
    @song_history = SongHistory.destroy(params[:id])
    redirect_to song_histories_path
  end

  def show
    @song_history = SongHistory.find(params[:id])
    @song_versions = @song_history.song_versions
  end

  private

    def song_history
      @song_history ||= SongHistory.find(params[:id])
    end

    def create_params
      params[:song_history].permit(:proto_name)
    end

    def update_params
      params[:song_history].permit(:proto_name)
    end

end

app/controllers/song_versions_controller.rb
class SongVersionsController < ApplicationController

  respond_to :html

  def new
    respond_with @song_version = song_versions.new
  end

  def create
    respond_with song_versions.create(permited_params), location: [song_history]
  end

  def show
    respond_with song_version
  end

  def edit
    respond_with song_version
  end

  def update
    respond_with song_history, song_versions.update(params[:id], permited_params)
  end

  def destroy
    respond_with song_version.destroy, location: [@song_history]
  end

  private
    def permited_params
      params[:song_version].permit(:name)
    end

    def song_history
      @song_history ||= SongHistory.find(params[:song_history_id])
    end

    def song_version
      @song_version ||= song_history.song_versions.find(params[:id])
    end

    def song_versions
      song_history.song_versions
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Song Manager</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/song_histories/_form.html.erb
<%= simple_form_for @song_history do |f| %>
  <%= f.input :proto_name %>
  <%= f.button :submit %>
<% end %>

app/views/song_histories/create.html.erb
<%= @song_history.proto_name %>

app/views/song_histories/index.html.erb
<nav>
  <%= link_to 'New!', new_song_history_path %>
</nav>

<ol>
  <% for song_history in @song_histories %>
    <li>
      <%= link_to song_history.proto_name,
          song_history_path(song_history.id),
          id: "show-#{song_history.id}-sh" %>

      <%= link_to 'remove',
          song_history_path(song_history.id),
          method: :delete,
          id: "remove-#{song_history.id}-sh" %>
    </li>
  <% end %>
</ol>

app/views/song_histories/new.html.erb
<%= simple_form_for @song_history do |f| %>
  <%= f.input :proto_name %>
  <%= f.button :submit %>
<% end %>

app/views/song_histories/show.html.erb
<nav>
  <%= @song_history.proto_name %> |
  <%= link_to 'new!', new_song_history_song_version_path(@song_history.id), id: 'new-sv' %>
</nav>

<ol>
  <% @song_versions.each do |s| %>
    <li>
      <%= link_to s.name,
        song_history_song_version_path(@song_history.id, s.id),
        id: "version-#{s.song_history_id}-#{s.id}-"
      %>
    </li>
  <% end %>
</ol>

app/views/song_versions/_form.html.erb
<%= simple_form_for [@song_history, @song_version] do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/song_versions/edit.html.erb
<%= render 'form' %>

app/views/song_versions/new.html.erb
<%= render 'form' %>

app/views/song_versions/show.html.erb
<nav>
  <%= link_to 'Delete', song_history_song_version_path(@song_history, @song_version), method: :delete, id: 'del-sv' %>
</nav>

<ol>
  <li><%= @song_version.name %></li>
</ol>